title: "Biblioteca del Proyecto VLIR-VG"
description: "Productos del proyecto"
theme: just-the-docs

url: "https://xavier1b.github.io"

# Configuración básica
search_enabled: true
heading_anchors: true

# Enlaces del footer
footer_content: "Copyright &copy; 2025 Proyecto VLIR-VG."

# Orden de navegación
nav_order: 1
# Configuración de navegación
nav_external_links:
  - title: "Presentación"
    url: "/presentacion"
  - title: "Inicio"
    url: "/"
    children:
      - title: "Marco legal, Políticas y Protocolos"
        url: "/Marco legal, Políticas y Protocolos"
      - title: "Literatura especializada en VBG"
        url: "/Literatura especializada en VBG" 
      - title: "Productos de Investigación"
        url: "/Productos de Investigación"

# Para que se muestren los children automáticamente
nav_fold: true
