title: "Biblioteca del Proyecto VLIR-VG"
description: "Productos del proyecto"
theme: just-the-docs
url: "https://xavier1b.github.io"

collections:
  pages:
    output: true
    permalink: /:path/

# Para que se muestren los children automáticamente
nav_fold: true

# Configuración básica
search_enabled: true
heading_anchors: true

# Logo (si lo tienes)
logo: "/assets/images/proyecto.jpg"

# Enlaces del footer
footer_content: "Copyright &copy; 2025 Proyecto VLIR-VG."

